import type { EventUser } from "~/routes/events.wakiaiai/types/event-user"

export const eventUsers: EventUser[] = [
  {
    name: "ことばのあや",
    types: ["SHOP", "EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_kotobanoaya.jpg?alt=media&token=4501e176-39fa-4a6d-9ccc-aa79ebd41dd1",
    twitterId: "ko_to_ba_no_aya",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "カッコ",
    types: ["SHOP", "EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiai2_kakowara.jpg?alt=media&token=bb06210f-ad6c-4331-98de-9f163315a8ad",
    twitterId: "kakowara365",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "双月書房",
    types: ["SHOP", "EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_ancient_katana.png?alt=media&token=f8a39bcc-35dc-48e5-bcbb-3afdfb22a309",
    twitterId: null,
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "碧燕工房",
    types: ["SHOP", "EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_swallownavy.png?alt=media&token=bbc8deb4-58bc-4a53-92ef-de57f4976c89",
    twitterId: "swallownavy",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "アワートAI",
    types: ["SHOP", "EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_ourt_ai.png?alt=media&token=3d4f564d-0405-449e-8e15-1b44fa27651d",
    twitterId: "ourt_ai",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "イロミライ(IROMIRAI)",
    types: ["SHOP", "EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_iromirai.jpg?alt=media&token=799d9520-90ac-4b17-b6da-971643157680",
    twitterId: "iromiraijp",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "東海アニメ研究会「Zeele」",
    types: ["SHOP", "EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_TokaiAnime.jpg?alt=media&token=88e157d2-1432-470f-81aa-9fd6705d8688",
    twitterId: "TokaiAnime",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "Aipictors",
    types: ["SHOP", "EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_aipictors.png?alt=media&token=2f56d7b3-dda9-46d7-8dcf-087b1262086f",
    twitterId: "Aipictors",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "晴レル屋",
    types: ["SHOP"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_KARA_Beee.png?alt=media&token=931ede5c-b35f-4998-a35d-835e1674f412",
    twitterId: "KARA_Beee",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "ふしめろ",
    types: ["SHOP"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_hushinomiya.jpg?alt=media&token=6624efc0-04b2-4209-9ddb-045efbd3d8e4",
    twitterId: "@hushinomiya",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "サムネイル・ストーリーズ",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_thumbnailstorie.png?alt=media&token=af323540-a95e-43c6-9aeb-75e87656b651",
    twitterId: "thumbnailstorie",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "Heliotrope; Eccentric",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_Heliotrope.png?alt=media&token=96afa3e5-5697-4a12-ac63-7480ec37cd0b",
    twitterId: "8484ff_42",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "褐色眼鏡工房",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_novelai_oekaki.jpg?alt=media&token=6415e924-1ed8-449c-949e-a065243cc42e",
    twitterId: "novelai_oekaki",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "クラフ",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_AIPhotoCrafter.jpg?alt=media&token=386c6510-11f2-41d7-9e39-2df35409b1ee",
    twitterId: "AIPhotoCrafter",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "Wood.Pecker",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_Wood_Pecker_.jpg?alt=media&token=7d3779e0-7931-484c-b728-da0e48c9556b",
    twitterId: "Wood_Pecker_",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "神田樹",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_kanda.png?alt=media&token=1fc88203-5e41-43fb-93e7-9d917036d92c",
    twitterId: "kitsunekan",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "おたひ",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_otahiiiiiiiiii.png?alt=media&token=20f06564-203f-4764-bb42-96b80bd933c4",
    twitterId: "otahiiiiiiiiii",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "りぉみ@AIart",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_rio_scarlet_AI.jpg?alt=media&token=ac759420-1be5-4360-bb70-8a433f16c027",
    twitterId: "rio_scarlet_AI",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "Ayumi (Midnight Cupcakes)",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_ayumi_t820.jpg?alt=media&token=4030379c-d227-453c-9f43-67f9bcb493bc",
    twitterId: "ayumi_t820",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "杉ぃ丸AI絵師",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_urasiboridm.jpg?alt=media&token=fba4dd98-e2d3-4541-9fd0-e2b76308a921",
    twitterId: "urasiboridm",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "すくらっぷのやまだ",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_fghjkl71903498.jpg?alt=media&token=0c3d664c-96e5-45f5-b3ab-7d48c1e4f265",
    twitterId: "fghjkl71903498",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "ンチアーネのアトリエ",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_ShunkaCule.png?alt=media&token=3bc69687-e927-4760-abe3-dbb805d745dc",
    twitterId: "ShunkaCule",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "Narumi",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_InaseAiIst.png?alt=media&token=369d3a13-dce6-40d0-b63d-9ef52232d33c",
    twitterId: "InaseAiIst",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "滝川海老郎",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_syuribox.png?alt=media&token=ae3d963a-5f11-46a9-851c-940ac4859d33",
    twitterId: "syuribox",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "ぐす",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_vqmp7pwqbefqkog.jpg?alt=media&token=5f20bc73-765a-4889-8473-57ab777426a4",
    twitterId: "vqmp7pwqbefqkog",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "ももろみ",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_tmh_red.png?alt=media&token=28a35fc5-93ba-4fb6-b63e-2295aeb2cdfe",
    twitterId: "tmh_red",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "響　晶",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_HibikiAkira0616.png?alt=media&token=7aaaa9dd-3618-4557-94ec-57992293abc7",
    twitterId: "HibikiAkira0616",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },

  {
    name: "さつき＠うさぎ好き",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fmasukarasulove.gif?alt=media&token=d25ff6ce-b206-4bf9-a9dc-d2dd0e85a5cd",
    twitterId: "masukarasulove",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
]
