version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      # Use Japan Standard Time (UTC +09:00)
      timezone: "Asia/Tokyo"
    target-branch: "main"
    labels:
      - "Dependabot"
    group:
      production-dependencies:
        dependency-type: production
          patterns:
            - "*"
      dev-dependencies:
        dependency-type: development
          patterns:
            - "*"
