changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🏕 Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: Dependabot
      labels:
        - Dependabot
