import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages"
// @ts-ignore - the server build file is generated by `remix vite:build`
import * as build from "../build/server"

const remixHandler = createPagesFunctionHandler({ build })

export const onRequest: PagesFunction = async (ctx) => {
  try {
    return await remixHandler(ctx)
  } catch (err) {
    console.error("unhandled error", err)

    const url = new URL(ctx.request.url)
    if (url.searchParams.get("__retry") === "1") throw err

    await new Promise((r) => setTimeout(r, 500))
    url.searchParams.set("__retry", "1")
    return Response.redirect(url.toString(), 302)
  }
}
