steps:
  - name: bash
    script: |
      #!/usr/bin/env bash
      if [ "${IS_PRODUCTION}" = "false" ]; then
        mv .env.staging .env
      fi
      rm -rf .env.production.local
    env:
      - "IS_PRODUCTION=$_IS_PRODUCTION"
      - "TRIGGER_ID=$_TRIGGER_ID"
    id: Env
  - name: bash
    script: |
      #!/usr/bin/env bash
      sed -i 's/lefthook install/echo/g' package.json
    id: PostInstall
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - "--builder=gcr.io/buildpacks/builder:v1"
      - "--network=cloudbuild"
      - "--path=."
      - "--env"
      - SENTRY_AUTH_TOKEN=$_SENTRY_AUTH_TOKEN
    id: Buildpack
    entrypoint: pack
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  # machineType: "E2_HIGHCPU_8"
substitutions:
  _PLATFORM: managed
  _DEPLOY_REGION: asia-northeast1
  _AR_HOSTNAME: asia-northeast1-docker.pkg.dev
  _IS_PRODUCTION: "true"
  _TRIGGER_ID: "debug"
  _SERVICE_NAME: "aipictors"
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - aipictors
