import type { EventUser } from "~/routes/($lang).events/types/event-user"

export const eventUsers: EventUser[] = [
  {
    name: "ことばのあや",
    types: ["SHOP", "EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiai2_kotobanoaya_160.jpg?alt=media&token=e3b4a56c-23cc-4be5-93a4-2adea6e05109",
    twitterId: "ko_to_ba_no_aya",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "カッコ",
    types: ["SHOP", "EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiai2_kakowara.jpg?alt=media&token=bb06210f-ad6c-4331-98de-9f163315a8ad",
    twitterId: "kakowara365",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "双月書房",
    types: ["SHOP", "EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_ancient_katana.png?alt=media&token=f8a39bcc-35dc-48e5-bcbb-3afdfb22a309",
    twitterId: null,
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "アワートAI",
    types: ["SHOP", "EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_ourt_ai.png?alt=media&token=3d4f564d-0405-449e-8e15-1b44fa27651d",
    twitterId: "ourtAI_moto",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "イロミライ(IROMIRAI)",
    types: ["SHOP", "EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_iromirai.jpg?alt=media&token=799d9520-90ac-4b17-b6da-971643157680",
    twitterId: "iromiraijp",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "晴レル屋",
    types: ["SHOP"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_KARA_Beee.png?alt=media&token=931ede5c-b35f-4998-a35d-835e1674f412",
    twitterId: "KARA_Beee",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "サムネイル・ストーリーズ",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_thumbnailstorie.png?alt=media&token=af323540-a95e-43c6-9aeb-75e87656b651",
    twitterId: "thumbnailstorie",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "Heliotrope; Eccentric",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_Heliotrope.png?alt=media&token=96afa3e5-5697-4a12-ac63-7480ec37cd0b",
    twitterId: "8484ff_42",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "褐色眼鏡工房",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_novelai_oekaki.jpg?alt=media&token=6415e924-1ed8-449c-949e-a065243cc42e",
    twitterId: "novelai_oekaki",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "クラフ",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_AIPhotoCrafter.jpg?alt=media&token=386c6510-11f2-41d7-9e39-2df35409b1ee",
    twitterId: "AIPhotoCrafter",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "Wood.Pecker",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_Wood_Pecker_.jpg?alt=media&token=7d3779e0-7931-484c-b728-da0e48c9556b",
    twitterId: "Wood_Pecker_",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "Aipictors",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai3_aipictors.png?alt=media&token=2f56d7b3-dda9-46d7-8dcf-087b1262086f",
    twitterId: "Aipictors",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
]
