import type { EventUser } from "@/routes/($lang).events/_types/event-user"

export const eventUsers: EventUser[] = [
  {
    name: "ことばのあや",
    types: ["SHOP", "EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiai2_kotobanoaya_160.jpg?alt=media&token=e3b4a56c-23cc-4be5-93a4-2adea6e05109",
    twitterId: "ko_to_ba_no_aya",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "カッコ",
    types: ["SHOP", "EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiai2_kakowara.jpg?alt=media&token=bb06210f-ad6c-4331-98de-9f163315a8ad",
    twitterId: "kakowara365",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "ふしめろ",
    types: ["SHOP", "EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fhushinomiya.png?alt=media&token=a8e6c6f2-49f1-42b3-962a-6040c6215393",
    twitterId: "hushinomiya",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "晴レル屋",
    types: ["SHOP"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai2_KARA_Beee_160.png?alt=media&token=15ac947e-c5ac-443a-ba35-8ebd7224185a",
    twitterId: "KARA_Beee",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "碧燕工房",
    types: ["SHOP"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fswallownavy.png?alt=media&token=8c5ca929-8de0-420e-a85e-ece65367a687",
    twitterId: "swallownavy",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "ホミー",
    types: ["SHOP"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fxiukuchuan30329.jpg?alt=media&token=fe0007a3-d2be-4b59-b274-83ffe66fd317",
    twitterId: "xiukuchuan30329",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "Wood.Pecker",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiai2_Wood_Pecker_160.jpg?alt=media&token=f96c838e-85f6-4429-9be4-356327c3d584",
    twitterId: "Wood_Pecker_",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "ざくろ舞",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai2_Kilroy.jpg?alt=media&token=a98136f9-0cd9-49a3-be52-a88187bdd70a",
    twitterId: null,
    aipictorsId: null,
    siteURL: "https://bsky.app/profile/zacromai.bsky.social",
    siteTitle: "BlueSky",
    links: [],
  },
  {
    name: "滝川 海老郎",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai2_syuribox.png?alt=media&token=12785028-ea9a-455c-a10f-16dd80fd132d",
    twitterId: "syuribox",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "haga",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fhagamight.jpg?alt=media&token=ca3fda49-6b45-495c-b265-aa8c10ddcb6b",
    twitterId: "hagamight",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "七瀬葵",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Faoinanase07.png?alt=media&token=631e4768-34cf-41a6-8df4-d95f384e9a28",
    twitterId: "aoinanase07",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "lion sey(セイ)",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Flion_sey.png?alt=media&token=2b589fbe-6b22-41de-a618-b0ab6a61a587",
    twitterId: "lion_sey",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "さつき＠AIお絵描き(うさぎ好き)",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fmasukarasulove.gif?alt=media&token=d25ff6ce-b206-4bf9-a9dc-d2dd0e85a5cd",
    twitterId: "masukarasulove",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "Aipictors",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai2_aipictors_160.png?alt=media&token=6f7a88ee-78ae-49cd-8476-940f2d2f4707",
    twitterId: "Aipictors",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
  {
    name: "プロンプトン",
    types: ["EXHIBIT"],
    message: null,
    iconImageURL:
      "https://firebasestorage.googleapis.com/v0/b/kwkjsui8ghyt93ai5feb.appspot.com/o/events%2Fwakiaiai%2Fwakiaiai2_prompton_160.jpg?alt=media&token=0c91c377-890f-43c1-9c93-12c8568f993e",
    twitterId: "promptonio",
    aipictorsId: null,
    siteURL: null,
    siteTitle: null,
    links: [],
  },
]
