name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "app/**/*"
      - "graphql/**/*"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
      - run: time bun i --frozen-lockfile

      - name: Prebuild
        run: time bun run predev

      - name: Run Test
        run: time bun run build
