name: CI + Dependabot Auto-Merge

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  # 1️⃣ どんな PR でもテストを実行
  test:
    uses: ./.github/workflows/test.yml   # ←再利用ワークフロー

  # 2️⃣ Dependabot から来た PR だけ自動マージ
  dependabot-auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    needs: test                         # テストが通ったら続行
    steps:
      - name: Fetch metadata
        id: prepare
        uses: dependabot/fetch-metadata@v1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge (patch only)
        if: ${{ steps.prepare.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --merge "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
