name: Dependabot Auto Merge
on:
  pull_request:
    branches: ["main"]


permissions:
  contents: write

jobs:
  call-workflow-test:
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: ./.github/workflows/test.yml
  run:
    runs-on: ubuntu-latest
    needs: call-workflow-test
    steps:
      - name: prepare
        id: prepare
        uses: dependabot/fetch-metadata@v1.6.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: merge
        if: ${{ steps.prepare.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --merge ${{github.event.pull_request.html_url}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
