name: Daily Release

on:
  schedule:
    - cron: '00 15 * * *'  # 日本時間の23:59はUTCの14:59
  workflow_dispatch:  # 手動でのトリガーも可能

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get current date
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        id: date
        run: echo "release_date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.date.outputs.release_date }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}