name: deploy-storybook

on:
  push:
    branches:
      - main
    paths:
      - "stories/**/*"

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: install packages
        run: bun install

      - name: build storybook
        run: bun run build-storybook

      - name: deploy storybook
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: Storybook
          folder: storybook-static
