name: Unit Tests & Code Quality
on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: install deps
        run: bun i --ignore-scripts --frozen-lockfile

      - name: cache node modules
        id: cache-node_modules
        uses: actions/cache/save@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('bun.lockb') }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: restore cache node modules
        id: cache-node_modules
        uses: actions/cache/restore@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ hashFiles('bun.lockb') }}

      - name: Install deps
        run: bun install --ignore-scripts --frozen-lockfile
      
      - name: Build GraphQL Code
        run: bun graphql-codegen-esm --config codegen.ts

      - name: Lint
        run: bunx oxlint@latest --jsx-a11y-plugin --react-perf-plugin

      - name: Run Test
        run: bun test

  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v1
        with:
          version: latest

      - name: Run Biome
        run: biome ci app

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: cache node modules
        id: cache-node_modules
        uses: actions/cache/restore@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ hashFiles('bun.lockb') }}

      - name: Install deps
        run: bun install --ignore-scripts --frozen-lockfile

      - name: Build GraphQL Code
        run: bun graphql-codegen-esm --config codegen.ts

      - name: Typecheck
        run: bun run check
