name: Unit Tests & Code Quality
on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: install deps
        run: bun i --ignore-scripts --frozen-lockfile
      - name: cache node modules
        id: cache-node_modules
        uses: actions/cache/save@v4
        if: ${{github.ref_name == 'main'}}
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ hashFiles('bun.lockb') }}

  test:
    runs-on: ubuntu-latest
    needs: setup
    env:
      VITE_MICRO_CMS_API_KEY: ${{ secrets.VITE_MICRO_CMS_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: restore cache node modules
        id: cache-node_modules
        uses: actions/cache/restore@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ hashFiles('bun.lockb') }}
      - name: Install deps
        run: rm -rf node_modules && bun install --ignore-scripts --frozen-lockfile
      - name: Lint
        run: bunx oxlint@latest --jsx-a11y-plugin --react-perf-plugin
      - name: Run Test
        run: bun test

  typecheck:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: cache node modules
        id: cache-node_modules
        uses: actions/cache/restore@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ hashFiles('bun.lockb') }}
      - name: Install deps
        run: rm -rf node_modules && bun install --ignore-scripts --frozen-lockfile
      - name: Typecheck
        run: bun run check
