name: Unit Tests

on:
  push:
    branches:
      - main
    paths:
      - "app/**/*"
      - "graphql/**/*"
  pull_request:
    branches:
      - main
    paths:
      - "app/**/*"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
      - run: time bun i --frozen-lockfile

      - name: Prebuild
        run: time bun predev

      - name: Lint
        run: bunx oxlint@latest --nextjs-plugin

      - name: Run Type Cheking
        run: time bun check

      - name: Run Test
        run: time bun test
