name: Unit Tests

on:
  push:
    branches:
      - dev

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install
        run: bun install
      
      - name: Prebuild
        run: bun run prebuild
      
      - name: Run Type Cheking
        run: bun run check
      
      - name: Run Test
        run: bun run test
