name: Unit Tests

on:
  push:
    branches:
      - main
    paths:
      - "app/**/*"
  pull_request:
    branches:
      - main
    paths:
      - "app/**/*"

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install

      - name: Install
        run: time pnpm install
      
      - name: Prebuild
        run: time pnpm run predev
      
      # - name: Run Type Cheking
      #   run: time pnpm run check push時に無くても実行するので、一度消して様子見
      
      - name: Run Test
        run: time pnpm run test
