name: Unit Tests & Code Quality

on:
  push:
    branches:
      - main
    paths:
      - "app/**/*"
      - "graphql/**/*"
  pull_request:
    branches:
      - main
    paths:
      - "app/**/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
      - run: time bun i --frozen-lockfile

      - name: Lint
        run: bunx oxlint@latest --nextjs-plugin

      - name: Run Type Cheking
        run: time bun run check

      - name: Run Test
        run: time bun test
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v1
        with:
          version: latest
      - name: Run Biome
        run: biome ci app graphql
