name: Unit Tests

on:
  push:
    branches:
      - main
    paths:
      - "app/**/*"
  pull_request:
    branches:
      - main
    paths:
      - "app/**/*"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
      - run: time bun install

      - name: Install
        run: time bun install
      
      - name: Prebuild
        run: time bun run predev
      
      - name: Run Type Cheking
        run: time bun run check
      
      - name: Run Test
        run: time bun run test
